spring:
  application:
    name: user-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8070
# redis配置迁移到了nacos
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database: 0
server:
  port: 8083
  servlet:
    context-path: /user-service
# mybatis的配置迁移到了nacos
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
logging:
  level:
    com.niuniu.user.feignclient.OrderClient: debug
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
#seata客户端配置
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: public
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: user-service-fescar-service-group
  service:
    vgroup-mapping:
      user-service-fescar-service-group: default
  data-source-proxy-mode: AT

