spring:
  application:
    name: store-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8070
server:
  port: 8086
  servlet:
    context-path: /store-service
logging:
  level:
    com.niuniu.user.feignclient.OrderClient: debug
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
#seata客户端配置
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: public
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: store-service-fescar-service-group
  service:
    vgroup-mapping:
      store-service-fescar-service-group: default
  data-source-proxy-mode: AT

