spring:
  application:
    name: product-service
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8085
  servlet:
    context-path: /product-service
#openfeign连接池
#feign:
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false
logging:
  root:
    level: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#seata客户端配置
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: public
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: product-service-fescar-service-group
  service:
    vgroup-mapping:
      product-service-fescar-service-group: default
  data-source-proxy-mode: XA
